# Generated by Django 4.0.5 on 2022-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('BirthDay', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('ZipCode', models.IntegerField()),
                ('LandLine', models.BigIntegerField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('isInfected', models.BooleanField()),
                ('isDiabetes', models.BooleanField()),
                ('isCardio', models.BooleanField()),
                ('isAllergic', models.BooleanField()),
                ('otherInput', models.CharField(max_length=100)),
            ],
        ),
    ]
