# Generated by Django 4.0.5 on 2022-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='otherInput',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
